<?php

namespace ShopBundle\Repository;

/**
 * CacheCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CacheCodesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInfo($row){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ch')
            ->from('ShopBundle:CacheCodes', 'ch')
            ->orderBy('ch.id', 'ASC')
            ->setFirstResult($row)
            ->setMaxResults(1000)
            ->getQuery()->getResult()
            ;
    }

    public function findUpdated($ids){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ch')
            ->from('ShopBundle:CacheCodes', 'ch')
            ->where('ch.id IN (:ids)')
            ->orderBy('ch.id', 'ASC')
            ->setParameter('ids', $ids)
            ->getQuery()->getResult()
            ;
    }

    public function updateData($id, $name){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('ShopBundle:CacheCodes', 'ch')
            ->set('ch.name', ':nm')
            ->where('ch.id = :id')
            ->setParameter('nm', $name)
            ->setParameter('id', $id)

            ->getQuery()->execute()
            ;
    }
}
