<?php

namespace ShopBundle\Repository;

/**
 * CompanyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
