<?php

namespace ShopBundle\Repository;

/**
 * EmailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailsRepository extends \Doctrine\ORM\EntityRepository
{
}
