<?php

namespace AppBundle\Repository;

/**
 * ConnectionCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionCodesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActual() {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c.code')
            ->from('AppBundle:ConnectionCodes', 'c')
            ->getQuery()->getArrayResult()

            ;

    }
}
