<?php

namespace AppBundle\Repository;

/**
 * IdramGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdramGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
