<?php

namespace AppBundle\Repository;

/**
 * IdramInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdramInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
