<?php

namespace AppBundle\Repository;

/**
 * ReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByUsers($useId) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('r')
            ->from('AppBundle:Reference', 'r')
            ->leftJoin('r.user', 'u')
            ->where('u.id = :uId')
            ->orderBy('r.created', 'DESC')
            ->setParameter('uId', $useId)
            ->getQuery()->getResult()

            ;
    }
}
