<?php

namespace AppBundle\Repository;

/**
 * ReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceItemRepository extends \Doctrine\ORM\EntityRepository
{

}
