shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [http, https]

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    schemes:  [http, https]

bag_rest:
    type:     rest
    resource: ShopBundle\Controller\Rest\RestMainController
    schemes:  [http, https]


#app_rest:
#    type:     rest
#    resource: "@AppBundle/Controller/Rest/ItemController.php"
#
#app_rest_project:
#    type:     rest
#    resource: "@AppBundle/Controller/Rest/ProjectController.php"
#
#app_rest_pattern:
#    type:     rest
#    resource: "@AppBundle/Controller/Rest/PatternController.php"

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    schemes:  [http, https]

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    schemes:  [http, https]

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    schemes:  [http, https]

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    schemes:  [http, https]

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    schemes:  [http, https]

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    schemes:  [http, https]

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    schemes:  [http, https]

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    schemes:  [http, https]
