# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

      app.convert.excel:
          class: ShopBundle\Services\ConvertExcel
          arguments: ['@service_container']

      app.admin.user:
          class: ShopBundle\Admin\UserAdmin
          arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
          tags:
              - {name: sonata.admin, manager_type: orm, group: User, label: User, show_in_dashboard: true }

      sonata.admin.company:
          class: ShopBundle\Admin\CompanyAdmin
          arguments: [~, ShopBundle\Entity\Company, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Menu, label: Company, show_in_dashboard: true }

      sonata.admin.company.categiry:
          class: ShopBundle\Admin\CompanyCategoryAdmin
          arguments: [~, ShopBundle\Entity\CompanyCategory, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Menu, label: Company Category, show_in_dashboard: true }

      sonata.admin.address:
          class: ShopBundle\Admin\AddressAdmin
          arguments: [~, ShopBundle\Entity\Address, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Menu, label: Address, show_in_dashboard: true }

      sonata.admin.phone:
          class: ShopBundle\Admin\PhoneAdmin
          arguments: [~, ShopBundle\Entity\Phone, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Menu, label: Phone, show_in_dashboard: true }
      sonata.admin.email:
          class: ShopBundle\Admin\EmailAdmin
          arguments: [~, ShopBundle\Entity\Emails, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Menu, label: Emails, show_in_dashboard: true }
      sonata.admin.position:
          class: ShopBundle\Admin\PositionAdmin
          arguments: [~, ShopBundle\Entity\Position, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Menu, label: Position, show_in_dashboard: true }

      sonata.admin.person:
          class: ShopBundle\Admin\PersonAdmin
          arguments: [~, ShopBundle\Entity\Person, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Menu, label: Person, show_in_dashboard: true }

      sonata.admin.maksain:
          class: ShopBundle\Admin\CacheCodesAdmin
          arguments: [~, ShopBundle\Entity\CacheCodes, ~]
          tags:
              - {name: sonata.admin, manager_type: orm, group: Tax, label: Tax, show_in_dashboard: true }
